###
POST http://localhost:3000/api/users  HTTP/1.1
Content-Type: application/json

{
    "avatarPath": "url_path",
    "username":"user-salt-1",
    "email": "salt1@test.cl",
    "password": "salt1234",
    "passwordConfirmation": "salt1234"
}
###
POST http://vercel-typescript-express-api-fawn.vercel.app/api/advance  HTTP/1.1
Content-Type: application/json

{
    "user": "640953569fa099a60d45e998"
}
###
POST http://vercel-typescript-express-api-fawn.vercel.app/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "salt1@test.cl",
    "password": "salt1234"
}

###
PATCH http://localhost:3000/api/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg0YTVmZTlmY2FjYTdhN2FhNjhjNzQiLCJpYXQiOjE2ODY0NDg0MDJ9.lsgNRyw6EU8plFXoVMpGgWakArs-Q9F7z1-7QXdPqrA
Content-Type: application/json

{
  "avatarPath": "ruta/al/avatar.jpg"
}

###
PATCH http://localhost:3000/api/advance/641c906388ff5ffc4d813aa0/numero_transiciones_conocimiento_bajo HTTP/1.1
Content-Type: application/json

{
    "641c906388ff5ffc4d813aa0":"1,0,0,0,0,0,0,0,0,0"
}

###
PATCH http://localhost:3000/api/users/password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg0YTVmZTlmY2FjYTdhN2FhNjhjNzQiLCJpYXQiOjE2ODY0NDg0MDJ9.lsgNRyw6EU8plFXoVMpGgWakArs-Q9F7z1-7QXdPqrA
Content-Type: application/json

{
    "newPassword":"test1234"
}

###
GET http://localhost:3000/api/users/check-email/t@test.cl HTTP/1.1
Content-Type: application/json
 

Content-Type: application/json

###
GET https://dle.rae.es/srv/search?w={hola} HTTP/1.1
Content-Type: application/json

###
GET https://dle.rae.es/data/anagram?w=amor HTTP/1.1
Content-Type: application/json
 

