###
POST http://vercel-typescript-express-api-fawn.vercel.app/api/users  HTTP/1.1
Content-Type: application/json

{
    "avatarPath": "url_path",
    "username":"sebastianjorc",
    "email": "login@login.co",
    "password": "password1",
    "passwordConfirmation": "password1"
}
###
POST http://vercel-typescript-express-api-fawn.vercel.app/api/advance  HTTP/1.1
Content-Type: application/json

{
    "user": "640953569fa099a60d45e998"
}
###
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "login@login",
    "password": "password1!"
}

###
PATCH http://localhost:3000/api/users/640953569fa099a60d45e998/palette HTTP/1.1
Content-Type: application/json

{
    "palette": "rosa-verde"
}

###
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/users/check-email/t@test.cl HTTP/1.1
Content-Type: application/json
